In [3]:
import pandas as pd
import requests

In [4]:
BASE_URL = "https://data-charts-api.hexlet.app"

START = "2023-03-01"
END = "2023-09-01"

In [5]:
visits_response = requests.get(
    f"{BASE_URL}/visits",
    params={"begin": START, "end": END},
    timeout=30
)

visits_response.raise_for_status()

visits_data = visits_response.json()

In [6]:
registrations_response = requests.get(
    f"{BASE_URL}/registrations",
    params={"begin": START, "end": END},
    timeout=30
)

registrations_response.raise_for_status()

registrations_data = registrations_response.json()

In [7]:
print("Посещения:")
print(type(visits_data))
print("Количество записей:", len(visits_data))

print("\nРегистрации:")
print(type(registrations_data))
print("Количество записей:", len(registrations_data))

Посещения:
<class 'list'>
Количество записей: 263459

Регистрации:
<class 'list'>
Количество записей: 21836

In [9]:
visits_data[:3]
registrations_data[:3]

[{'datetime': '2023-03-01T07:40:13',
  'user_id': '2e0f6bb8-b029-4f45-a786-2b53990d37f1',
  'email': 'ebyrd@example.org',
  'platform': 'web',
  'registration_type': 'google'},
 {'datetime': '2023-03-01T13:14:00',
  'user_id': 'f007f97c-9d8b-48b5-af08-119bb8f6d9b6',
  'email': 'knightgerald@example.org',
  'platform': 'web',
  'registration_type': 'email'},
 {'datetime': '2023-03-01T03:05:50',
  'user_id': '24ff46ae-32b3-4a74-8f27-7cf0b8f32f15',
  'email': 'cherylthompson@example.com',
  'platform': 'web',
  'registration_type': 'apple'}]

In [10]:
visits = pd.DataFrame(visits_data)
registrations = pd.DataFrame(registrations_data)
display(visits.head())
display(registrations.head())

,visit_id,platform,user_agent,datetime
0,a34b3b68-a1ad-4f18-ace9-0644d5a1db7d,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-29T04:37:53
1,a34b3b68-a1ad-4f18-ace9-0644d5a1db7d,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,2023-03-27T15:30:43
2,7b03818c-9a90-47d2-b866-0aea56dc17a7,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,2023-03-29T14:30:51
3,7b03818c-9a90-47d2-b866-0aea56dc17a7,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,2023-03-27T12:35:13
4,aa27c5b7-4eba-4496-8bf7-2dd5ebc7a560,web,Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7...,2023-03-29T03:39:58

,datetime,user_id,email,platform,registration_type
0,2023-03-01T07:40:13,2e0f6bb8-b029-4f45-a786-2b53990d37f1,ebyrd@example.org,web,google
1,2023-03-01T13:14:00,f007f97c-9d8b-48b5-af08-119bb8f6d9b6,knightgerald@example.org,web,email
2,2023-03-01T03:05:50,24ff46ae-32b3-4a74-8f27-7cf0b8f32f15,cherylthompson@example.com,web,apple
3,2023-03-01T00:04:47,3e9914e1-5d73-4c23-b25d-b59a3aeb2b60,halldavid@example.org,web,email
4,2023-03-01T18:31:52,27f875fc-f8ce-4aeb-8722-0ecb283d0760,denise86@example.net,web,google

In [11]:
print("Размер таблицы посещений:", visits.shape)
print("Размер таблицы регистраций:", registrations.shape)
visits.info()
registrations.info()

Размер таблицы посещений: (263459, 4)
Размер таблицы регистраций: (21836, 5)
<class 'pandas.DataFrame'>
RangeIndex: 263459 entries, 0 to 263458
Data columns (total 4 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   visit_id    263459 non-null  str
 1   platform    263459 non-null  str
 2   user_agent  263459 non-null  str
 3   datetime    263459 non-null  str
dtypes: str(4)
memory usage: 48.8 MB
<class 'pandas.DataFrame'>
RangeIndex: 21836 entries, 0 to 21835
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   datetime           21836 non-null  str
 1   user_id            21836 non-null  str
 2   email              21836 non-null  str
 3   platform           21836 non-null  str
 4   registration_type  21836 non-null  str
dtypes: str(5)
memory usage: 2.6 MB

In [12]:
visits["datetime"] = pd.to_datetime(visits["datetime"], errors="coerce")
registrations["datetime"] = pd.to_datetime(
    registrations["datetime"],
    errors="coerce"
)

In [13]:
display(visits.describe(include="all"))
display(registrations.describe(include="all"))

,visit_id,platform,user_agent,datetime
count,263459,263459,263459,263459
unique,146085,4,32,NaN
top,efb03b0e-a057-4de0-9541-26b9982a521e,web,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109...,NaN
freq,4,236301,13623,NaN
mean,NaN,NaN,NaN,2023-06-01 06:22:22.042044
min,NaN,NaN,NaN,2023-03-01 00:00:43
25%,NaN,NaN,NaN,2023-04-13 19:45:03
50%,NaN,NaN,NaN,2023-06-03 12:23:27
75%,NaN,NaN,NaN,2023-07-17 22:09:08
max,NaN,NaN,NaN,2023-08-31 23:52:57

,datetime,user_id,email,platform,registration_type
count,21836,21836,21836,21836,21836
unique,NaN,21836,20868,3,4
top,NaN,2e0f6bb8-b029-4f45-a786-2b53990d37f1,ujones@example.com,android,email
freq,NaN,1,6,10582,8996
mean,2023-05-29 10:17:02.002747,NaN,NaN,NaN,NaN
min,2023-03-01 00:04:47,NaN,NaN,NaN,NaN
25%,2023-04-12 01:49:47.500000,NaN,NaN,NaN,NaN
50%,2023-05-26 13:22:09,NaN,NaN,NaN,NaN
75%,2023-07-15 17:26:30.500000,NaN,NaN,NaN,NaN
max,2023-08-31 23:43:26,NaN,NaN,NaN,NaN